sudo: required
dist: trusty

language: node_js

node_js:
  - 8
  - 6

script:
  - yarn run test
  - yarn run build

notifications:
  email:
    on_failure: change

after_success: 'yarn run reportcoverage'

cache:
  yarn: true
